AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation Script for ECS service and Task Definition"

Parameters:
  BucketName:
    Description: Kindly enter the name of the bucket containing environment files.
    Type: "String"
    Default: "knit-uat-backend-environment-files"
  ClusterName:
    Description: Kindly enter the name of ecs cluster.
    Type: "String"
    Default: "knit-backend-uat"
  ContainerName:
    Description: Kindly enter the name of the container
    Type: "String"
    Default: "knit-uat-survey-response-insertion-worker-container"
  FamilyName:
    Description: Kindly enter the name of the application so that it can be recognised in creating revisions
    Type: "String"
    Default: "knit-uat-survey-response-insertion-worker"
  Image:
    Description: Kindly enter the name of the image along with tag
    Type: "String"
  PortMapping:
    Description: Kindly enter the port number for your application
    Type: "Number"
    Default: "80"
  ServiceName:
    Description: Kindly enter the service name
    Type: "String"
    Default: "knit-uat-survey-response-insertion-worker"
  QueueName:
    Description: Kindly enter the Queue name
    Type: "String"
    Default: "uat-survey-responses-queue"

Resources:
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      RoleName: knit-uat-survey-response-insertion-worker-ecs-task-role
      Policies:
        - PolicyName: AmazonECSTaskRoleknitUatWorkerApiPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'autoscaling:CompleteLifecycleAction'
                  - 'autoscaling:DeleteLifecycleHook'
                  - 'autoscaling:DescribeAutoScalingGroups'
                  - 'autoscaling:DescribeLifecycleHooks'
                  - 'autoscaling:PutLifecycleHook'
                  - 'autoscaling:RecordLifecycleActionHeartbeat'
                  - 'autoscaling:CreateAutoScalingGroup'
                  - 'autoscaling:CreateOrUpdateTags'
                  - 'autoscaling:UpdateAutoScalingGroup'
                  - 'autoscaling:EnableMetricsCollection'
                  - 'autoscaling:DescribePolicies'
                  - 'autoscaling:DescribeScheduledActions'
                  - 'autoscaling:DescribeNotificationConfigurations'
                  - 'autoscaling:SuspendProcesses'
                  - 'autoscaling:ResumeProcesses'
                  - 'autoscaling:AttachLoadBalancers'
                  - 'autoscaling:AttachLoadBalancerTargetGroups'
                  - 'autoscaling:PutScalingPolicy'
                  - 'autoscaling:PutScheduledUpdateGroupAction'
                  - 'autoscaling:PutNotificationConfiguration'
                  - 'autoscaling:PutWarmPool'
                  - 'autoscaling:DescribeScalingActivities'
                  - 'autoscaling:DeleteAutoScalingGroup'
                  - 'ec2:DescribeInstances'
                  - 'ec2:DescribeInstanceStatus'
                  - 'ec2:TerminateInstances'
                  - 'tag:GetResources'
                  - 'sns:Publish'
                  - 'cloudwatch:DescribeAlarms'
                  - 'cloudwatch:PutMetricAlarm'
                  - 'elasticloadbalancing:DescribeLoadBalancerAttributes'
                  - 'elasticloadbalancing:DescribeTargetGroupAttributes'
                  - 'elasticloadbalancing:DescribeLoadBalancers'
                  - 'elasticloadbalancing:DescribeInstanceHealth'
                  - 'elasticloadbalancing:RegisterInstancesWithLoadBalancer'
                  - 'elasticloadbalancing:DeregisterInstancesFromLoadBalancer'
                  - 'elasticloadbalancing:DescribeTargetGroups'
                  - 'elasticloadbalancing:DescribeTargetHealth'
                  - 'elasticloadbalancing:RegisterTargets'
                  - 'elasticloadbalancing:DeregisterTargets'
                  - 'cloudwatch:PutMetricData'
                  - 'ec2:DescribeVolumes'
                  - 'ec2:DescribeTags'
                  - 'logs:PutLogEvents'
                  - 'logs:DescribeLogStreams'
                  - 'logs:DescribeLogGroups'
                  - 'logs:CreateLogStream'
                  - 'logs:CreateLogGroup'
                  - 'secretsmanager:ListSecrets'
                  - 'cloudwatch:PutMetricData'
                  - 'ses:SendEmail'
                  - 's3:ListBucket'
                  - 's3:GetBucketLocation'
                  - 'ecs:GetTaskProtection'
                  - 'ecs:UpdateTaskProtection'
                Resource: '*'
              - Effect: 'Allow'
                Action:
                  - 'cognito-idp:CreateGroup'
                  - 'cognito-idp:ListIdentityProviders'
                  - 'cognito-idp:CreateIdentityProvider'
                  - 'cognito-idp:ListUserPoolClients'
                  - 'cognito-idp:ListUsersInGroup'
                  - 'cognito-idp:DescribeUserPool'
                  - 'cognito-idp:ListGroups'
                  - 'cognito-idp:DescribeIdentityProvider'
                  - 'cognito-idp:UpdateGroup'
                  - 'cognito-idp:DescribeUserPoolClient'
                  - 'cognito-idp:ListUsers'
                  - 'cognito-idp:ForgotPassword'
                  - 'cognito-idp:GlobalSignOut'
                  - 'cognito-idp:ConfirmForgotPassword'
                  - 'cognito-idp:GetUser'
                  - 'cognito-idp:ConfirmSignUp'
                  - 'cognito-idp:ListDevices'
                  - 'cognito-idp:GetGroup'
                  - 'cognito-idp:ListUserPools'
                  - 'cognito-idp:RespondToAuthChallenge'
                  - 'cognito-idp:UpdateUserAttributes'
                  - 'cognito-idp:DescribeUserPoolDomain'
                  - 'cognito-idp:UpdateDeviceStatus'
                  - 'cognito-idp:ChangePassword'
                  - 'cognito-idp:ConfirmDevice'
                  - 'cognito-idp:ResendConfirmationCode'
                Resource:
                  - !Sub 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/us-east-1_q808SLXW4'
                  - !Sub 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/us-east-1_ISM7nmxX9'
              - Effect: 'Allow'
                Action: 'ssm:GetParameter'
                Resource: 'arn:aws:ssm:*:*:parameter/AmazonCloudWatch-*'
              - Effect: 'Allow'
                Action: 's3:*'
                Resource:
                  - 'arn:aws:s3:::com.knit.dev/*'
                  - 'arn:aws:s3:::com.knit.dev'
              - Effect: 'Allow'
                Action: 'ec2:Describe*'
                Resource: !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/i-08d99b6d30264f0bb'
              - Effect: 'Allow'
                Action:
                  - 'secretsmanager:DescribeSecret'
                  - 'secretsmanager:GetResourcePolicy'
                  - 'secretsmanager:List'
                  - 'secretsmanager:GetSecretValue'
                Resource:
                  - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:knit_secret_manager-qEWqil"
                  - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:knit_uat_secrete_manager-fBKEar"
              - Effect: 'Allow'
                Action:
                  - 'sqs:DeleteMessage'
                  - 'sqs:ReceiveMessage'
                  - 'secretsmanager:GetSecretValue'
                  - 'sqs:ListDeadLetterSourceQueues'
                  - 'sqs:PurgeQueue'
                  - 'sqs:SendMessage'
                  - 'sqs:ListQueueTags'
                  - 'sqs:GetQueueUrl'
                  - 'sqs:ChangeMessageVisibility'
                Resource:
                  - !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:uat-survey-responses-queue'
                  - !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:uat-survey-responses-queue-DLQ'
              - Effect: 'Allow'
                Action: 'lambda:InvokeFunction'
                Resource: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:*:*'

  Task:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref FamilyName
      Cpu: 2048
      Memory: 4096
      NetworkMode: awsvpc
      TaskRoleArn: !GetAtt TaskRole.Arn
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/knit-uat-ecs-taskexecution-role'
      ContainerDefinitions:
        - Name: !Ref ContainerName
          Image: !Ref Image
          EnvironmentFiles:
            - Type: "s3"
              Value:
                !Join [
                  "",
                  [
                    "arn:aws:s3:::",
                    !Ref BucketName,
                    "/",
                    !Ref ServiceName,
                    ".env",
                  ],
                ]
          PortMappings:
            - ContainerPort: !Ref PortMapping
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref CloudwatchLogsGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: knit-uat-ecs

  CloudwatchLogsGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Join
        - "-"
        - - ECSLogGroup
          - !Ref "AWS::StackName"
      RetentionInDays: 90

  PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: vpc-074bb0b6f81390144
      GroupDescription: for ecs containers

  PublicService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Ref ServiceName
      TaskDefinition: !Ref Task
      Cluster: !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${ClusterName}"
      LaunchType: FARGATE
      DesiredCount: 1
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 70
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - subnet-03f7e0d21159d4cfe
            - subnet-0ce07f51b93037168
          SecurityGroups:
            - !Ref PrivateSecurityGroup

  ScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: PublicService
    Properties:
      ServiceNamespace: 'ecs'
      ScalableDimension: 'ecs:service:DesiredCount'
      ResourceId: !Sub 'service/${ClusterName}/${ServiceName}'
      MinCapacity: 1
      MaxCapacity: 30
      RoleARN: !Sub 'arn:aws:iam::${AWS::AccountId}:role/knit-uat-auto-scaling-role'

  ScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn: ScalableTarget
    Properties:
      PolicyName: !Sub 'knit-uat-survey-response-worker-${ClusterName}-${ServiceName}-service-scale-up-policy'
      PolicyType: StepScaling
      ResourceId: !Sub 'service/${ClusterName}/${ServiceName}'
      ScalableDimension: 'ecs:service:DesiredCount'
      ServiceNamespace: 'ecs'
      StepScalingPolicyConfiguration:
        AdjustmentType: 'ExactCapacity'
        StepAdjustments:
          - MetricIntervalLowerBound: 0
            MetricIntervalUpperBound: 50
            ScalingAdjustment: 1
          - MetricIntervalLowerBound: 50
            MetricIntervalUpperBound: 200
            ScalingAdjustment: 4
          - MetricIntervalLowerBound: 200
            MetricIntervalUpperBound: 500
            ScalingAdjustment: 6
          - MetricIntervalLowerBound: 500
            MetricIntervalUpperBound: 1000
            ScalingAdjustment: 10
          - MetricIntervalLowerBound: 1000
            MetricIntervalUpperBound: 1500
            ScalingAdjustment: 12
          - MetricIntervalLowerBound: 1500
            MetricIntervalUpperBound: 2000
            ScalingAdjustment: 15
          - MetricIntervalLowerBound: 2000
            MetricIntervalUpperBound: 3000
            ScalingAdjustment: 20
          - MetricIntervalLowerBound: 3000
            ScalingAdjustment: 30
        Cooldown: 60

  scalingAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub knit-uat-survey-response-worker-service-high-message-count-${ClusterName}-${ServiceName}-alarm
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Dimensions:
        - Name: QueueName
          Value : !Ref 'QueueName'
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref ScalingPolicy