AWSTemplateFormatVersion: 2010-09-09

Parameters:
  EnvironmentName:
    Type: String

Resources:
  InternalServiceRequestErrorHandlerSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue
        Fn::Sub: "knit-${EnvironmentName}-vpc"
      GroupDescription: !Sub "knit-${EnvironmentName} Security group for fallback lambda function that calls ECS services"
  
  AllowAccessToPrivateServicesSgRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      SourceSecurityGroupId:
        Fn::GetAtt:
          - InternalServiceRequestErrorHandlerSg
          - GroupId
      GroupId: !ImportValue
        Fn::Sub: "knit-${EnvironmentName}-private-alb-sg"

Outputs:
  InternalServiceRequestErrorHandlerSg:
    Value: !Ref InternalServiceRequestErrorHandlerSg
    Export:
      Name: !Sub "knit-${EnvironmentName}-internal-service-error-handler-sg"