AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template to create an SQS queue."

Parameters:
  EnvironmentName:
    Type: String

Resources:
  SurveyResponsesDLQ:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: !Sub "${EnvironmentName}-survey-responses-queue-DLQ" 
      DelaySeconds: 2
      MessageRetentionPeriod: 1209600
      VisibilityTimeout: 50
      ReceiveMessageWaitTimeSeconds: 0
      SqsManagedSseEnabled: true

  SurveyResponsesDLQQueuePolicy:
    Type: "AWS::SQS::QueuePolicy"
    Properties:
      Queues:
        - !Ref SurveyResponsesDLQ
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "OwnerStatement"
            Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "SQS:*"
            Resource: !GetAtt SurveyResponsesDLQ.Arn

  SurveyResponsesQueue:
    Type: "AWS::SQS::Queue"
    DependsOn: SurveyResponsesDLQ
    Properties:
      QueueName: !Sub "${EnvironmentName}-survey-responses-queue"
      DelaySeconds: 120
      MessageRetentionPeriod: 864000
      VisibilityTimeout: 1200
      ReceiveMessageWaitTimeSeconds: 5
      # KmsDataKeyReusePeriodSeconds: 300
      SqsManagedSseEnabled: true
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SurveyResponsesDLQ.Arn
        maxReceiveCount: 10

  SurveyResponsesQueuePolicy:
    Type: "AWS::SQS::QueuePolicy"
    Properties:
      Queues:
        - !Ref SurveyResponsesQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "OwnerStatement"
            Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "SQS:*"
            Resource: !GetAtt SurveyResponsesQueue.Arn
  BetaRetryRequestDLQ:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: !Sub "${EnvironmentName}-retry-request-DLQ" 
      DelaySeconds: 0
      MessageRetentionPeriod: 1209600
      VisibilityTimeout: 900
      ReceiveMessageWaitTimeSeconds: 0
      SqsManagedSseEnabled: true

  BetaRetryRequestDLQQueuePolicy:
    Type: "AWS::SQS::QueuePolicy"
    Properties:
      Queues:
        - !Ref BetaRetryRequestDLQ
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "OwnerStatement"
            Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "SQS:*"
            Resource: !GetAtt BetaRetryRequestDLQ.Arn

  BetaRetryRequestQueue:
    Type: "AWS::SQS::Queue"
    DependsOn: BetaRetryRequestDLQ
    Properties:
      QueueName: !Sub "${EnvironmentName}-retry-request-queue"
      DelaySeconds: 0
      MessageRetentionPeriod: 1209600
      VisibilityTimeout: 900
      ReceiveMessageWaitTimeSeconds: 0
      # KmsDataKeyReusePeriodSeconds: 300
      SqsManagedSseEnabled: true
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt BetaRetryRequestDLQ.Arn
        maxReceiveCount: 10

  BetaRetryRequestQueuePolicy:
    Type: "AWS::SQS::QueuePolicy"
    Properties:
      Queues:
        - !Ref BetaRetryRequestQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "OwnerStatement"
            Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "SQS:*"
            Resource: !GetAtt BetaRetryRequestQueue.Arn
