AWSTemplateFormatVersion: 2010-09-09

Parameters:
  EnvironmentName:
    Type: String
    Default: "stg"
  TemplateBucketName:
    Type: String

Resources:
  genericLogGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.amazonaws.com/cloudwatch/generic-log-groups.yml"
      Tags:
        - Key: stackId
          Value: !Ref AWS::StackId
      Parameters:
        EnvironmentName: !Ref EnvironmentName
