AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation Script for ECS service and Task Definition"

Parameters:
  EnvironmentName:
    Type: String
  BucketName:
    Type: "String"
  ClusterName:
    Type: "String"
  ContainerName:
    Type: "String"
  FamilyName:
    Type: "String"
  ServiceName:
    Type: "String"
  Image:
    Type: "String"
  PortMapping:
    Type: "Number"
  WindowsBastionSG:
    Type: String
  CognitoUserPoolId:
    Type: String

Resources:
  DataExchangeServiceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue
        Fn::Sub: "knit-${EnvironmentName}-vpc"
      GroupDescription: Data-Exchange-Service-SG
      SecurityGroupIngress:
        - SourceSecurityGroupId: !Ref WindowsBastionSG # beta-service-testing-windows-bastion only for private services
          IpProtocol: tcp
          FromPort: !Ref PortMapping
          ToPort: !Ref PortMapping
        - SourceSecurityGroupId: !ImportValue
            Fn::Sub: "knit-${EnvironmentName}-insights-fast-api-internal-communication-sg"
          IpProtocol: tcp
          FromPort: !Ref PortMapping
          ToPort: !Ref PortMapping
        - SourceSecurityGroupId: !ImportValue
            Fn::Sub: "knit-${EnvironmentName}-data-exchange-service-internal-communication-sg"
            
          IpProtocol: tcp
          FromPort: !Ref PortMapping
          ToPort: !Ref PortMapping
        - SourceSecurityGroupId: sg-0539d1793e9e925d6
          IpProtocol: tcp
          FromPort: !Ref PortMapping
          ToPort: !Ref PortMapping


  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      RoleName: !Sub "${ServiceName}-ecs-task-role"
      Policies:
        - PolicyName: !Sub "${ServiceName}-ecs-task-role-policy"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - autoscaling:CompleteLifecycleAction
                  - autoscaling:DeleteLifecycleHook
                  - autoscaling:DescribeAutoScalingGroups
                  - autoscaling:DescribeLifecycleHooks
                  - autoscaling:PutLifecycleHook
                  - autoscaling:RecordLifecycleActionHeartbeat
                  - autoscaling:CreateAutoScalingGroup
                  - autoscaling:CreateOrUpdateTags
                  - autoscaling:UpdateAutoScalingGroup
                  - autoscaling:EnableMetricsCollection
                  - autoscaling:DescribePolicies
                  - autoscaling:DescribeScheduledActions
                  - autoscaling:DescribeNotificationConfigurations
                  - autoscaling:SuspendProcesses
                  - autoscaling:ResumeProcesses
                  - autoscaling:AttachLoadBalancers
                  - autoscaling:AttachLoadBalancerTargetGroups
                  - autoscaling:PutScalingPolicy
                  - autoscaling:PutScheduledUpdateGroupAction
                  - autoscaling:PutNotificationConfiguration
                  - autoscaling:PutWarmPool
                  - autoscaling:DescribeScalingActivities
                  - autoscaling:DeleteAutoScalingGroup
                  - ec2:DescribeInstances
                  - ec2:DescribeInstanceStatus
                  - ec2:TerminateInstances
                  - tag:GetResources
                  - sns:Publish
                  - cloudwatch:DescribeAlarms
                  - cloudwatch:PutMetricAlarm
                  - elasticloadbalancing:DescribeLoadBalancerAttributes
                  - elasticloadbalancing:DescribeTargetGroupAttributes
                  - elasticloadbalancing:DescribeLoadBalancers
                  - elasticloadbalancing:DescribeInstanceHealth
                  - elasticloadbalancing:RegisterInstancesWithLoadBalancer
                  - elasticloadbalancing:DeregisterInstancesFromLoadBalancer
                  - elasticloadbalancing:DescribeTargetGroups
                  - elasticloadbalancing:DescribeTargetHealth
                  - elasticloadbalancing:RegisterTargets
                  - elasticloadbalancing:DeregisterTargets
                  - cloudwatch:PutMetricData
                  - ec2:DescribeVolumes
                  - ec2:DescribeTags
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                  - logs:DescribeLogGroups
                  - logs:CreateLogStream
                  - logs:CreateLogGroup
                  - secretsmanager:ListSecrets
                  - s3:ListBucket
                  - s3:GetBucketLocation
                  - cloudwatch:PutMetricData
                  - ses:SendEmail
                  - ses:GetTemplate
                  - ses:ListTemplates
                  - ses:SendTemplatedEmail
                Resource: "*"
              - Effect: Allow
                Action:
                  - cognito-idp:CreateGroup
                  - cognito-idp:ListIdentityProviders
                  - cognito-idp:CreateIdentityProvider
                  - cognito-idp:ListUserPoolClients
                  - cognito-idp:ListUsersInGroup
                  - cognito-idp:DescribeUserPool
                  - cognito-idp:ListGroups
                  - cognito-idp:DescribeIdentityProvider
                  - cognito-idp:UpdateGroup
                  - cognito-idp:DescribeUserPoolClient
                  - cognito-idp:GetGroup
                  - cognito-idp:ListUsers
                  - cognito-idp:ForgotPassword
                  - cognito-idp:GlobalSignOut
                  - cognito-idp:ConfirmForgotPassword
                  - cognito-idp:GetUser
                  - cognito-idp:ConfirmSignUp
                  - cognito-idp:ListDevices
                  - cognito-idp:ListUserPools
                  - cognito-idp:RespondToAuthChallenge
                  - cognito-idp:UpdateUserAttributes
                  - cognito-idp:DescribeUserPoolDomain
                  - cognito-idp:UpdateDeviceStatus
                  - cognito-idp:ChangePassword
                  - cognito-idp:ConfirmDevice
                  - cognito-idp:ResendConfirmationCode
                Resource:
                  - !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUserPoolId}"
              - Effect: Allow
                Action:
                  - secretsmanager:DescribeSecret
                  - secretsmanager:GetResourcePolicy
                  - secretsmanager:ListSecretVersionIds
                  - secretsmanager:GetSecretValue
                Resource:
                  - !ImportValue
                    Fn::Sub: "knit-${EnvironmentName}-secret-manager"
              - Effect: Allow
                Action:
                  - s3:ListAllMyBuckets
                Resource:
                  - "arn:aws:s3:::*"
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource:
                  - "arn:aws:ssm:*:*:parameter/AmazonCloudWatch-*"
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - arn:aws:s3:::com.knit.prod
                  - arn:aws:s3:::com.knit.prod/*
              - Effect: Allow
                Action:
                  - sqs:DeleteMessage
                  - sqs:ReceiveMessage
                  - sqs:ListDeadLetterSourceQueues
                  - sqs:SendMessage
                  - sqs:ListQueueTags
                  - sqs:GetQueueUrl
                  - sqs:ChangeMessageVisibility
                Resource:
                  - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${EnvironmentName}-retry-request-DLQ"
                  - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${EnvironmentName}-retry-request-queue"

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref FamilyName
      Cpu: 2048
      Memory: 4096
      NetworkMode: awsvpc
      TaskRoleArn: !GetAtt TaskRole.Arn
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue
        Fn::Sub: "knit-${EnvironmentName}-ecs-task-execution-role"
      ContainerDefinitions:
        - Name: !Ref ContainerName
          Image: !Ref Image
          EnvironmentFiles:
            - Type: "s3"
              Value: !Join [ "", ["arn:aws:s3:::",!Ref BucketName,"/",!Ref ServiceName,".env" ]]
          PortMappings:
            - ContainerPort: !Ref PortMapping
              Protocol: tcp
          LogConfiguration:
              LogDriver: awslogs
              Options:
                awslogs-group: !Ref CloudwatchLogsGroup
                awslogs-region: !Ref 'AWS::Region'
                awslogs-stream-prefix: knit-beta-ecs
  
  CloudwatchLogsGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Join 
        - '-'
        - - ECSLogGroup
          - !Ref 'AWS::StackName'
      RetentionInDays: 90

  DiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Description: Discovery Service for the Application
      DnsConfig:
        RoutingPolicy: MULTIVALUE
        DnsRecords:
          - TTL: 60
            Type: A
      HealthCheckCustomConfig:
        FailureThreshold: 1
      Name: !Ref ServiceName
      NamespaceId: ns-fcmspbrkfuqa57gx

  PrivateService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Ref ServiceName
      TaskDefinition: !Ref TaskDefinition
      Cluster: !ImportValue
        Fn::Sub: "knit-${EnvironmentName}-ecs-cluster"
      LaunchType: FARGATE
      DesiredCount: 1
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 70
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - !ImportValue
              Fn::Sub: "knit-${EnvironmentName}-private-subnet-1"
            - !ImportValue
              Fn::Sub: "knit-${EnvironmentName}-private-subnet-2"
            - !ImportValue
              Fn::Sub: "knit-${EnvironmentName}-private-subnet-3"
          SecurityGroups:
            - !Ref DataExchangeServiceSG
            - !ImportValue
              Fn::Sub: "knit-${EnvironmentName}-data-exchange-service-internal-communication-sg"
            
      ServiceRegistries:
        - RegistryArn: !GetAtt DiscoveryService.Arn

  # Autoscalling Part
  ScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn:
      - PrivateService
    Properties:
      ServiceNamespace: "ecs"
      ScalableDimension: "ecs:service:DesiredCount"
      ResourceId: !Sub "service/${ClusterName}/${ServiceName}"
      MinCapacity: 1
      MaxCapacity: 10
      RoleARN: !ImportValue
        Fn::Sub: "knit-${EnvironmentName}-ecs-task-autoscaling-role"

  ScaleDownPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn: ScalableTarget
    Properties:
      PolicyName: !Sub "${ServiceName}-scale-down-policy"
      PolicyType: StepScaling
      ResourceId: !Sub "service/${ClusterName}/${ServiceName}"
      ScalableDimension: "ecs:service:DesiredCount"
      ServiceNamespace: "ecs"
      StepScalingPolicyConfiguration:
        AdjustmentType: "PercentChangeInCapacity"
        StepAdjustments:
          - MetricIntervalUpperBound: 0
            ScalingAdjustment: -50
        MetricAggregationType: "Average"
        Cooldown: 30

  ScaleUpPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn: ScalableTarget
    Properties:
      PolicyName: !Sub "${ServiceName}-scale-up-policy"
      PolicyType: StepScaling
      ResourceId: !Sub "service/${ClusterName}/${ServiceName}"
      ScalableDimension: "ecs:service:DesiredCount"
      ServiceNamespace: "ecs"
      StepScalingPolicyConfiguration:
        AdjustmentType: "PercentChangeInCapacity"
        StepAdjustments:
          - MetricIntervalLowerBound: 40
            MetricIntervalUpperBound: 60
            ScalingAdjustment: 50
          - MetricIntervalLowerBound: 60
            MetricIntervalUpperBound: 75
            ScalingAdjustment: 70
          - MetricIntervalLowerBound: 75
            ScalingAdjustment: 100
        MetricAggregationType: "Maximum"
        Cooldown: 60

  LowCpuUsageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ServiceName}-low-cpu-alarm"
      AlarmDescription: !Sub "Low CPU utilization for service ${ServiceName} in cluster ${ClusterName}"
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Dimensions:
        - Name: ServiceName
          Value: !Sub "${ServiceName}"
        - Name: ClusterName
          Value: !Sub "${ClusterName}"
      Statistic: Maximum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 20
      ComparisonOperator: LessThanOrEqualToThreshold
      AlarmActions:
        - !Ref ScaleDownPolicy

  HighCpuUsageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ServiceName}-high-cpu-alarm"
      AlarmDescription: !Sub "High CPU utilization for service ${ServiceName} in cluster ${ClusterName}"
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Dimensions:
        - Name: ServiceName
          Value: !Sub "${ServiceName}"
        - Name: ClusterName
          Value: !Sub "${ClusterName}"
      Statistic: Maximum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref ScaleUpPolicy
