AWSTemplateFormatVersion: 2010-09-09
Description: "AWS CloudFormation template for creating S3"

Parameters:
  EnvironmentName:
    Type: String
  TemplateBucketName:
    Type: String

Resources:
  HostedZones:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.amazonaws.com/s3/application-data-s3-buckets.yaml"
      Tags:
        - Key: stackId
          Value: !Ref AWS::StackId
      Parameters:
        EnvironmentName: !Ref EnvironmentName
