AWSTemplateFormatVersion: "2010-09-09"
Description: "Basic network setup with VPC and subnets"

Parameters:
  EnvironmentName:
    Type: String
    Description: "Name of the environment"
    Default: "dev"
  VpcCidrBlock:
    Type: String
    Description: "CIDR block for the VPC"

Resources:
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      Tags:
        - Key: "Name"
          Value: !Sub "knit-${EnvironmentName}-vpc"

  PublicSubnet1:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref "VPC"
      AvailabilityZone: !Select [ 0, !GetAZs "us-east-1" ]
      CidrBlock: !Select [ 0, !Cidr [!Ref VpcCidrBlock, 256, 8]]
      Tags:
        - Key: "Name"
          Value: !Sub "knit-${EnvironmentName}-public-subnet1"

  PublicSubnet2:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref "VPC"
      AvailabilityZone: !Select [ 1, !GetAZs "us-east-1" ]
      CidrBlock: !Select [ 1, !Cidr [!Ref VpcCidrBlock, 256, 8]]
      Tags:
        - Key: "Name"
          Value: !Sub "knit-${EnvironmentName}-public-subnet2"

  PublicSubnet3:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref "VPC"
      AvailabilityZone: !Select [ 2, !GetAZs "us-east-1" ]
      CidrBlock: !Select [ 2, !Cidr [!Ref VpcCidrBlock, 256, 8]]
      Tags:
        - Key: "Name"
          Value: !Sub "knit-${EnvironmentName}-public-subnet3"

  PrivateSubnet1:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref "VPC"
      AvailabilityZone: !Select [ 0, !GetAZs "us-east-1" ]
      CidrBlock: !Select [ 3, !Cidr [!Ref VpcCidrBlock, 256, 8]]
      Tags:
        - Key: "Name"
          Value: !Sub "knit-${EnvironmentName}-private-subnet1"

  PrivateSubnet2:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref "VPC"
      AvailabilityZone: !Select [ 1, !GetAZs "us-east-1" ]
      CidrBlock: !Select [ 4, !Cidr [!Ref VpcCidrBlock, 256, 8]]
      Tags:
        - Key: "Name"
          Value: !Sub "knit-${EnvironmentName}-private-subnet2"

  PrivateSubnet3:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref "VPC"
      AvailabilityZone: !Select [ 2, !GetAZs "us-east-1" ]
      CidrBlock: !Select [ 5, !Cidr [!Ref VpcCidrBlock, 256, 8]]
      Tags:
        - Key: "Name"
          Value: !Sub "knit-${EnvironmentName}-private-subnet3"

Outputs:
  VPC:
    Description: "VPC ID"
    Value: !Ref "VPC"
    Export:
      Name: !Sub "knit-${EnvironmentName}-vpc"

  PublicSubnet1:
    Description: "Public Subnet 1 ID"
    Value: !Ref "PublicSubnet1"
    Export:
      Name: !Sub "knit-${EnvironmentName}-public-subnet-1"

  PublicSubnet2:
    Description: "Public Subnet 2 ID"
    Value: !Ref "PublicSubnet2"
    Export:
      Name: !Sub "knit-${EnvironmentName}-public-subnet-2"

  PublicSubnet3:
    Description: "Public Subnet 3 ID"
    Value: !Ref "PublicSubnet3"
    Export:
      Name: !Sub "knit-${EnvironmentName}-public-subnet-3"

  PrivateSubnet1:
    Description: "Private Subnet 1 ID"
    Value: !Ref "PrivateSubnet1"
    Export:
      Name: !Sub "knit-${EnvironmentName}-private-subnet-1"

  PrivateSubnet2:
    Description: "Private Subnet 2 ID"
    Value: !Ref "PrivateSubnet2"
    Export:
      Name: !Sub "knit-${EnvironmentName}-private-subnet-2"

  PrivateSubnet3:
    Description: "Private Subnet 3 ID"
    Value: !Ref "PrivateSubnet3"
    Export:
      Name: !Sub "knit-${EnvironmentName}-private-subnet-3"

