AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EnvironmentName:
    Type: String
    Description: "Name of the environment"

Resources:
  LambdaParentRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "knit_${EnvironmentName}_parent_internal_service_error_handler_role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub "AWSLambdaBasicExecutionRole-knit-${EnvironmentName}_parent_internal_service_error_handler_policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource:
                   - !Sub "arn:aws:logs:us-east-1:${AWS::AccountId}:log-group:/aws/lambda/knit_${EnvironmentName}_child_internal_service_error_handler:*"
              - Effect: "Allow"
                Action:
                  - "ec2:CreateNetworkInterface"
                  - "ec2:DeleteNetworkInterface"
                  - "ec2:DescribeNetworkInterfaces"
                Resource:
                  - "*"
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                Resource:
                  - "*"
      ManagedPolicyArns:
        - !ImportValue
            Fn::Sub: "Knit-${EnvironmentName}-deny-unused-regions-policy"
Outputs:
  LambdaParentRole:
    Description: "ARN of the vpc-flow-logs IAM role"
    Value: !GetAtt LambdaParentRole.Arn
    Export:
      Name: !Sub "Knit-${EnvironmentName}-parent-internal-service-error-handler-role-arn"