AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EnvironmentName:
    Type: String
    Description: "Name of the environment"

Resources:
  RestrictRegionsIAMPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "Knit-${EnvironmentName}-deny-unused-regions-policy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "DenyAllOutsideUSEast1"
            Effect: "Deny"
            NotAction:
              - "a4b:*"
              - "acm:*"
              - "aws-marketplace-management:*"
              - "aws-marketplace:*"
              - "aws-portal:*"
              - "budgets:*"
              - "ce:*"
              - "chime:*"
              - "cloudfront:*"
              - "config:*"
              - "cur:*"
              - "directconnect:*"
              - "ec2:DescribeRegions"
              - "ec2:DescribeTransitGateways"
              - "ec2:DescribeVpnGateways"
              - "fms:*"
              - "globalaccelerator:*"
              - "health:*"
              - "iam:*"
              - "importexport:*"
              - "kms:*"
              - "mobileanalytics:*"
              - "networkmanager:*"
              - "organizations:*"
              - "pricing:*"
              - "route53:*"
              - "route53domains:*"
              - "route53-recovery-cluster:*"
              - "route53-recovery-control-config:*"
              - "route53-recovery-readiness:*"
              - "s3:*"
              - "shield:*"
              - "sts:*"
              - "support:*"
              - "trustedadvisor:*"
              - "waf-regional:*"
              - "waf:*"
              - "wafv2:*"
              - "wellarchitected:*"
            Resource: "*"
            Condition:
              StringNotEquals:
                aws:RequestedRegion:
                  - "us-east-1"

Outputs:
  RestrictRegionsIAMPolicy:
    Value: !Ref RestrictRegionsIAMPolicy
    Export:
      Name: !Sub "Knit-${EnvironmentName}-deny-unused-regions-policy"