AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an AWS Secret Manager secret

Parameters:
  EnvironmentName:
    Type: String

Resources:
  SecretManager:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "knit_${EnvironmentName}_secrete_manager" 
  CiCdSecretManager:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "knit_${EnvironmentName}_cicd_secrete_manager" 

Outputs:
  SecretArn:
    Value: !Ref SecretManager
    Export:
      Name: !Sub "knit-${EnvironmentName}-secret-manager"
  CiCdSecretArn:
    Value: !Ref CiCdSecretManager
    Export:
      Name: !Sub "knit-${EnvironmentName}-cicd-secret-manager"