---
AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Script for Fargate

Parameters:
  EnvironmentName:
    Type: String
  LifecyclePolicyTextParameter:
    Type: String
    
Resources:

  AnalysisPlanDataExchangeECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName:  !Sub "knit-${EnvironmentName}-analysis-plan-data-exchange"
      RepositoryPolicyText:
        Version: 2012-10-17
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - "arn:aws:iam::020587470742:role/knit-beta-analysis-plan-data-exchange-code-build-role"
                - "arn:aws:iam::020587470742:role/knit-beta-analysis-plan-data-exchange-ecs-task-role"
                - "arn:aws:iam::020587470742:user/ravi-softvan"
                - "arn:aws:iam::020587470742:user/softvan-devops"
                - "arn:aws:iam::020587470742:user/vishal-softvan"
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload

  AuthServiceECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "knit-${EnvironmentName}-auth"
      RepositoryPolicyText:
        Version: 2012-10-17
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - "arn:aws:iam::020587470742:role/knit-beta-auth-ecs-task-role"
                - "arn:aws:iam::020587470742:role/knit-beta-backend-auth-code-build-role"
                - "arn:aws:iam::020587470742:user/ravi-softvan"
                - "arn:aws:iam::020587470742:user/softvan-devops"
                - "arn:aws:iam::020587470742:user/vishal-softvan"
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
      LifecyclePolicy:
        LifecyclePolicyText: !Ref LifecyclePolicyTextParameter

  InsightsFastApiServiceECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "knit-${EnvironmentName}-insights-fastapi"
      RepositoryPolicyText:
        Version: 2012-10-17
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - "arn:aws:iam::020587470742:role/knit-beta-insights-fastapi-code-build-role"
                - "arn:aws:iam::020587470742:role/knit-beta-insights-fastapi-ecs-task-role"
                - "arn:aws:iam::020587470742:user/ravi-softvan"
                - "arn:aws:iam::020587470742:user/softvan-devops"
                - "arn:aws:iam::020587470742:user/vishal-softvan"
                - "arn:aws:iam::020587470742:role/knit-beta-insights-fastapi-blue-green-ecs-task-role"
                - "arn:aws:iam::020587470742:role/knit-beta-insights-fastapi-blue-green-code-build-role"
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
      LifecyclePolicy:
        LifecyclePolicyText: !Ref LifecyclePolicyTextParameter

  SurveyResponseInsertionWorkerServiceECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "knit-${EnvironmentName}-survey-response-insertion-worker"
      RepositoryPolicyText:
        Version: 2012-10-17
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - "arn:aws:iam::020587470742:role/knit-beta-survey-response-insertion-worker-code-build-role"
                - "arn:aws:iam::020587470742:role/knit-beta-survey-response-insertion-worker-ecs-task-role"
                - "arn:aws:iam::020587470742:user/ravi-softvan"
                - "arn:aws:iam::020587470742:user/softvan-devops"
                - "arn:aws:iam::020587470742:user/vishal-softvan"
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
      LifecyclePolicy:
        LifecyclePolicyText: !Ref LifecyclePolicyTextParameter

  ExternalConnectServiceECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "knit-${EnvironmentName}-external-connect"
      RepositoryPolicyText:
        Version: 2012-10-17
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - "arn:aws:iam::020587470742:role/knit-beta-external-connect-code-build-role"
                - "arn:aws:iam::020587470742:role/knit-beta-external-connect-ecs-task-role"
                - "arn:aws:iam::020587470742:user/ravi-softvan"
                - "arn:aws:iam::020587470742:user/softvan-devops"
                - "arn:aws:iam::020587470742:user/vishal-softvan"
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
      LifecyclePolicy:
        LifecyclePolicyText: !Ref LifecyclePolicyTextParameter

  AIOEResponseAnalysisServiceECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "knit-${EnvironmentName}-ai-oe-response-analysis"
      RepositoryPolicyText:
        Version: 2012-10-17
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - "arn:aws:iam::020587470742:role/knit-beta-ai-oe-response-analysis-code-build-role"
                - "arn:aws:iam::020587470742:role/knit-beta-ai-oe-response-analysis-ecs-task-role "
                - "arn:aws:iam::020587470742:user/ravi-softvan"
                - "arn:aws:iam::020587470742:user/softvan-devops"
                - "arn:aws:iam::020587470742:user/vishal-softvan"
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
      LifecyclePolicy:
        LifecyclePolicyText: !Ref LifecyclePolicyTextParameter
          
  DataExchangeServiceECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "knit-${EnvironmentName}-data-exchange"
      RepositoryPolicyText:
        Version: 2012-10-17
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - "arn:aws:iam::020587470742:role/knit-beta-data-exchange-code-build-role"
                - "arn:aws:iam::020587470742:role/knit-beta-data-exchange-ecs-task-role"
                - "arn:aws:iam::020587470742:user/ravi-softvan"
                - "arn:aws:iam::020587470742:user/softvan-devops"
                - "arn:aws:iam::020587470742:user/vishal-softvan"
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
      LifecyclePolicy:
        LifecyclePolicyText: !Ref LifecyclePolicyTextParameter

  AIAnalysisPlanServiceECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "knit-${EnvironmentName}-ai-analysis-plan"
      RepositoryPolicyText:
        Version: 2012-10-17
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - "arn:aws:iam::020587470742:user/ravi-softvan"
                - "arn:aws:iam::020587470742:user/softvan-devops"
                - "arn:aws:iam::020587470742:user/vishal-softvan"
                - "arn:aws:iam::020587470742:role/knit-beta-ai-analysis-code-build-role"
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
      LifecyclePolicy:
        LifecyclePolicyText: !Ref LifecyclePolicyTextParameter
  
  AIInsightsServiceECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "knit-${EnvironmentName}-ai-insights"
      RepositoryPolicyText:
        Version: 2012-10-17
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - "arn:aws:iam::020587470742:role/knit-beta-ai-insights-code-build-role"
                - "arn:aws:iam::020587470742:role/knit-beta-ai-insights-ecs-task-role"
                - "arn:aws:iam::020587470742:user/ravi-softvan"
                - "arn:aws:iam::020587470742:user/softvan-devops"
                - "arn:aws:iam::020587470742:user/vishal-softvan"
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
      LifecyclePolicy:
        LifecyclePolicyText: !Ref LifecyclePolicyTextParameter

  AIOEAnalysisServiceECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "knit-${EnvironmentName}-ai-oe-analysis"
      RepositoryPolicyText:
        Version: 2012-10-17
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - "arn:aws:iam::020587470742:role/knit-beta-ai-oe-analysis-code-build-role"
                - "arn:aws:iam::020587470742:role/knit-beta-ai-oe-analysis-ecs-task-role"
                - "arn:aws:iam::020587470742:user/ravi-softvan"
                - "arn:aws:iam::020587470742:user/softvan-devops"
                - "arn:aws:iam::020587470742:user/vishal-softvan"
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
      LifecyclePolicy:
        LifecyclePolicyText: !Ref LifecyclePolicyTextParameter

  AISurveyGeneratorECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "knit-${EnvironmentName}-ai-survey-generator"
      RepositoryPolicyText:
        Version: 2012-10-17
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - "arn:aws:iam::020587470742:role/knit-beta-ai-survey-generator-code-build-role"
                - "arn:aws:iam::020587470742:role/knit-beta-ai-survey-generator-ecs-task-role"
                - "arn:aws:iam::020587470742:user/ravi-softvan"
                - "arn:aws:iam::020587470742:user/softvan-devops"
                - "arn:aws:iam::020587470742:user/vishal-softvan"
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
      LifecyclePolicy:
        LifecyclePolicyText: !Ref LifecyclePolicyTextParameter

  AIVideoAnalysissServiceECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "knit-${EnvironmentName}-ai-video-analysis"
      RepositoryPolicyText:
        Version: 2012-10-17
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - "arn:aws:iam::020587470742:role/knit-beta-ai-video-analysis-code-build-role"
                - "arn:aws:iam::020587470742:role/knit-beta-ai-video-analysis-ecs-task-role"
                - "arn:aws:iam::020587470742:user/ravi-softvan"
                - "arn:aws:iam::020587470742:user/softvan-devops"
                - "arn:aws:iam::020587470742:user/vishal-softvan"
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
      LifecyclePolicy:
        LifecyclePolicyText: !Ref LifecyclePolicyTextParameter
