---
AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Script for Fargate

Parameters:
  EnvironmentName:
    Type: String

Resources:
  EnvFileS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: StackId
          Value: !Ref AWS::StackId
      BucketName: !Sub "knit-${EnvironmentName}-backend-environment-files"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false

  ServiceDiscoveryPrivateNameSpace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties: 
      Name: !Sub "${EnvironmentName}"
      Vpc: !ImportValue
        Fn::Sub: "knit-${EnvironmentName}-vpc"
      Properties: 
        DnsProperties:
          SOA:
            TTL: 15

Outputs:
  EnvFileS3Bucket:
    Value: !Ref EnvFileS3Bucket
    Export:
      Name: !Sub "knit-${EnvironmentName}-backend-environment-files"
