AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation Script for ECS service and Task Definition"

Parameters:
  BucketName:
    Description: Kindly enter the name of the bucket containing environment files.
    Type: "String"
    Default: "knit-dev-backend-environment-files"
  ClusterName:
    Description: Kindly enter the name of ecs cluster.
    Type: "String"
    Default: "knit-backend-dev"
  ContainerName:
    Description: Kindly enter the name of the container
    Type: "String"
    Default: "knit-dev-insights-fastapi-container"
  FamilyName:
    Description: Kindly enter the name of the application so that it can be recognised in creating revisions
    Type: "String"
    Default: "knit-dev-insights-fastapi"
  Image:
    Description: Kindly enter the name of the image along with tag
    Type: "String"
  PortMapping:
    Description: Kindly enter the port number for your application
    Type: "Number"
    Default: "80"
  ServiceName:
    Description: Kindly enter the service name
    Type: "String"
    Default: "knit-dev-insights-fastapi"
  HealthCheckPath:
    Description: Kindly enter health check path for your application
    Type: "String"
    Default: "/api/docs"
  Priority:
    Description: Kindly enter priority number
    Type: "Number"
    Default: 5
  TargetGroupName:
    Description: Kindly enter the name of the Target group.
    Type: "String"
    Default: "knit-dev-insights-fastapi-tg"
  ApiAccessUrl:
    Type: "String"

Resources:
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      RoleName: knit-dev-insights-fastapi-ecs-task-role
      Policies:
        - PolicyName: AmazonECSTaskRoleknitDevInsightsFastApiPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - autoscaling:CompleteLifecycleAction
                  - autoscaling:DeleteLifecycleHook
                  - autoscaling:DescribeAutoScalingGroups
                  - autoscaling:DescribeLifecycleHooks
                  - autoscaling:PutLifecycleHook
                  - autoscaling:RecordLifecycleActionHeartbeat
                  - autoscaling:CreateAutoScalingGroup
                  - autoscaling:CreateOrUpdateTags
                  - autoscaling:UpdateAutoScalingGroup
                  - autoscaling:EnableMetricsCollection
                  - autoscaling:DescribePolicies
                  - autoscaling:DescribeScheduledActions
                  - autoscaling:DescribeNotificationConfigurations
                  - autoscaling:SuspendProcesses
                  - autoscaling:ResumeProcesses
                  - autoscaling:AttachLoadBalancers
                  - autoscaling:AttachLoadBalancerTargetGroups
                  - autoscaling:PutScalingPolicy
                  - autoscaling:PutScheduledUpdateGroupAction
                  - autoscaling:PutNotificationConfiguration
                  - autoscaling:PutWarmPool
                  - autoscaling:DescribeScalingActivities
                  - autoscaling:DeleteAutoScalingGroup
                  - ec2:DescribeInstances
                  - ec2:DescribeInstanceStatus
                  - ec2:TerminateInstances
                  - tag:GetResources
                  - sns:Publish
                  - cloudwatch:DescribeAlarms
                  - cloudwatch:PutMetricAlarm
                  - elasticloadbalancing:DescribeLoadBalancerAttributes
                  - elasticloadbalancing:DescribeTargetGroupAttributes
                  - elasticloadbalancing:DescribeLoadBalancers
                  - elasticloadbalancing:DescribeInstanceHealth
                  - elasticloadbalancing:RegisterInstancesWithLoadBalancer
                  - elasticloadbalancing:DeregisterInstancesFromLoadBalancer
                  - elasticloadbalancing:DescribeTargetGroups
                  - elasticloadbalancing:DescribeTargetHealth
                  - elasticloadbalancing:RegisterTargets
                  - elasticloadbalancing:DeregisterTargets
                  - cloudwatch:PutMetricData
                  - ec2:DescribeVolumes
                  - ec2:DescribeTags
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                  - logs:DescribeLogGroups
                  - logs:CreateLogStream
                  - logs:CreateLogGroup
                  - secretsmanager:ListSecrets
                  - s3:ListBucket
                  - s3:GetBucketLocation
                  - cloudwatch:PutMetricData
                  - ses:SendEmail
                  - ses:GetTemplate
                  - ses:ListTemplates
                  - ses:SendTemplatedEmail
                  - ecs:GetTaskProtection
                  - ecs:UpdateTaskProtection
                Resource: "*"
              - Effect: Allow
                Action:
                  - cognito-idp:CreateGroup
                  - cognito-idp:ListIdentityProviders
                  - cognito-idp:CreateIdentityProvider
                  - cognito-idp:ListUserPoolClients
                  - cognito-idp:ListUsersInGroup
                  - cognito-idp:DescribeUserPool
                  - cognito-idp:ListGroups
                  - cognito-idp:DescribeIdentityProvider
                  - cognito-idp:UpdateGroup
                  - cognito-idp:DescribeUserPoolClient
                  - cognito-idp:GetGroup
                  - cognito-idp:ListUsers
                  - cognito-idp:ForgotPassword
                  - cognito-idp:GlobalSignOut
                  - cognito-idp:ConfirmForgotPassword
                  - cognito-idp:GetUser
                  - cognito-idp:ConfirmSignUp
                  - cognito-idp:ListDevices
                  - cognito-idp:ListUserPools
                  - cognito-idp:RespondToAuthChallenge
                  - cognito-idp:UpdateUserAttributes
                  - cognito-idp:DescribeUserPoolDomain
                  - cognito-idp:UpdateDeviceStatus
                  - cognito-idp:ChangePassword
                  - cognito-idp:ConfirmDevice
                  - cognito-idp:ResendConfirmationCode
                Resource:
                  - !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/us-east-1_q808SLXW4"
                  - !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/us-east-1_ISM7nmxX9"
              - Effect: Allow
                Action:
                  - sqs:DeleteMessage
                  - sqs:ReceiveMessage
                  - sqs:ListDeadLetterSourceQueues
                  - sqs:PurgeQueue
                  - sqs:SendMessage
                  - sqs:ListQueueTags
                  - sqs:GetQueueUrl
                  - sqs:ChangeMessageVisibility
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:dev-survey-responses-queue"
                  - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:dev-survey-responses-queue-DLQ"
              - Effect: Allow
                Action:
                  - secretsmanager:DescribeSecret
                  - secretsmanager:GetResourcePolicy
                  - secretsmanager:ListSecretVersionIds
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub  'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:knit_secret_manager-qEWqil'
                  - !Sub  'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:knit_dev_secrete_manager-UMxdhf'
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:*:*"
              - Effect: Allow
                Action:
                  - s3:ListAllMyBuckets
                Resource:
                  - "arn:aws:s3:::*"
              - Effect: Allow
                Action:
                  - ec2:Describe*
                Resource:
                  - !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/i-0cfa888e74bec8d91"
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource:
                  - "arn:aws:s3:::knit-nginx-access-logs/Dev/"
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource:
                  - "arn:aws:ssm:*:*:parameter/AmazonCloudWatch-*"
              - Effect: Allow
                Action:
                  - s3:*
                  - ses:SendEmail
                Resource:
                  - arn:aws:s3:::com.knit.dev/*
                  - arn:aws:s3:::com.knit.dev
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - "arn:aws:lambda:us-east-1:020587470742:function:dev-knit-video-qualification-lambda"



  Task:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref FamilyName
      Cpu: 2048
      Memory: 4096
      NetworkMode: awsvpc
      TaskRoleArn: !GetAtt TaskRole.Arn
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/knit-backend-dev-ecs-taskexecution-role'
      ContainerDefinitions:
        - Name: !Ref ContainerName
          Image: !Ref Image
          EnvironmentFiles:
            - Type: "s3"
              Value:
                !Join [
                  "",
                  [
                    "arn:aws:s3:::",
                    !Ref BucketName,
                    "/",
                    !Ref ServiceName,
                    ".env",
                  ],
                ]
          PortMappings:
            - ContainerPort: !Ref PortMapping
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref CloudwatchLogsGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: knit-dev-ecs

  CloudwatchLogsGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Join
        - "-"
        - - ECSLogGroup
          - !Ref "AWS::StackName"
      RetentionInDays: 90

  PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: vpc-074bb0b6f81390144
      GroupDescription: for ecs containers
      SecurityGroupIngress:
        - SourceSecurityGroupId: sg-006e3455a3195dda4
          IpProtocol: tcp
          FromPort: !Ref PortMapping
          ToPort: !Ref PortMapping
        - SourceSecurityGroupId: sg-030986ef4959711c3
          IpProtocol: tcp
          FromPort: !Ref PortMapping
          ToPort: !Ref PortMapping

        - SourceSecurityGroupId: sg-0871c4bbb6ac69233
          IpProtocol: tcp
          FromPort: !Ref PortMapping
          ToPort: !Ref PortMapping

        - SourceSecurityGroupId: sg-0ed698f9c8f35d786
          IpProtocol: tcp
          FromPort: !Ref PortMapping
          ToPort: !Ref PortMapping

        - SourceSecurityGroupId: sg-0b673199777677130
          IpProtocol: tcp
          FromPort: !Ref PortMapping
          ToPort: !Ref PortMapping

        - SourceSecurityGroupId: sg-024fdca9e1a48c7ec
          IpProtocol: tcp
          FromPort: !Ref PortMapping
          ToPort: !Ref PortMapping

  DiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Description: Discovery Service for the Application
      DnsConfig:
        RoutingPolicy: MULTIVALUE
        DnsRecords:
          - TTL: 60
            Type: A
      HealthCheckCustomConfig:
        FailureThreshold: 1
      Name: !Ref ServiceName
      NamespaceId: ns-jasbuckusdlqlcnp

  PublicService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Ref ServiceName
      TaskDefinition: !Ref Task
      Cluster: !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${ClusterName}"
      LaunchType: FARGATE
      DesiredCount: 3
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 70
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - subnet-03f7e0d21159d4cfe
            - subnet-0ce07f51b93037168
          SecurityGroups:
            - !Ref PublicSecurityGroup
      LoadBalancers:
        - ContainerName: !Ref ContainerName
          ContainerPort: !Ref PortMapping
          TargetGroupArn: !Ref ServiceTargetGroup
      ServiceRegistries:
        - RegistryArn: !GetAtt DiscoveryService.Arn

  ServiceTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Ref TargetGroupName
      VpcId: vpc-074bb0b6f81390144
      Port: !Ref PortMapping
      Protocol: HTTP
      Matcher:
        HttpCode: 200
      HealthCheckIntervalSeconds: 60
      HealthCheckPath: !Ref HealthCheckPath
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 25
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      TargetType: ip
      TargetGroupAttributes: 
        - Key: load_balancing.algorithm.type
          Value: least_outstanding_requests

  ServiceListenerRule:
    Type: "AWS::ElasticLoadBalancingV2::ListenerRule"
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ServiceTargetGroup
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - !Ref ApiAccessUrl
      ListenerArn: !Sub "arn:aws:elasticloadbalancing:${AWS::Region}:${AWS::AccountId}:listener/app/knit-devuat-alb/3d51b2470f5ac635/1ede720b5b57e7b0"
      Priority: !Ref Priority

  ScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn:
      - PublicService
    Properties:
      ServiceNamespace: "ecs"
      ScalableDimension: "ecs:service:DesiredCount"
      ResourceId: !Sub "service/${ClusterName}/${ServiceName}"
      MinCapacity: 3
      MaxCapacity: 5
      RoleARN: !Sub "arn:aws:iam::${AWS::AccountId}:role/knit-dev-ecs-autoscaling-role"

  # Create scaling policies that describe how to scale the service up and down.
  ScaleDownPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn: ScalableTarget
    Properties:
      PolicyName: !Sub knit-dev-insights-fastapi-${ClusterName}-${ServiceName}-scale-down
      PolicyType: StepScaling
      ResourceId: !Sub "service/${ClusterName}/${ServiceName}"
      ScalableDimension: "ecs:service:DesiredCount"
      ServiceNamespace: "ecs"
      StepScalingPolicyConfiguration:
        AdjustmentType: "PercentChangeInCapacity"
        StepAdjustments:
          - MetricIntervalUpperBound: 0
            ScalingAdjustment: -50
        MetricAggregationType: "Average"
        Cooldown: 60

  ScaleUpPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn: ScalableTarget
    Properties:
      PolicyName: !Sub knit-dev-insights-fastapi-${ClusterName}-${ServiceName}-scale-up
      PolicyType: StepScaling
      ResourceId: !Sub "service/${ClusterName}/${ServiceName}"
      ScalableDimension: "ecs:service:DesiredCount"
      ServiceNamespace: "ecs"
      StepScalingPolicyConfiguration:
        AdjustmentType: "PercentChangeInCapacity"
        StepAdjustments:
          - MetricIntervalLowerBound: 40
            MetricIntervalUpperBound: 60
            ScalingAdjustment: 50
          - MetricIntervalLowerBound: 60
            MetricIntervalUpperBound: 75
            ScalingAdjustment: 50
          - MetricIntervalLowerBound: 75
            ScalingAdjustment: 50
        MetricAggregationType: "Maximum"
        Cooldown: 60

  # Create alarms to trigger the scaling policies
  LowCpuUsageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub knit-dev-insights-fastapi-service-low-cpu-${ClusterName}-${ServiceName}
      AlarmDescription: !Sub "Low CPU utilization for service ${ServiceName} in cluster ${ClusterName}"
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Dimensions:
        - Name: ServiceName
          Value: !Ref "ServiceName"
        - Name: ClusterName
          Value: !Ref "ClusterName"
      Statistic: Maximum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 20
      ComparisonOperator: LessThanOrEqualToThreshold
      AlarmActions:
        - !Ref ScaleDownPolicy

  HighCpuUsageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub knit-dev-insights-fastapi-service-high-cpu-${ClusterName}-${ServiceName}
      AlarmDescription: !Sub "High CPU utilization for service ${ServiceName} in cluster ${ClusterName}"
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Dimensions:
        - Name: ServiceName
          Value: !Ref "ServiceName"
        - Name: ClusterName
          Value: !Ref "ClusterName"
      Statistic: Maximum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref ScaleUpPolicy

Outputs:
  MySecurityGroup:
    Description: Security Group ID
    Value: !Ref PublicSecurityGroup
    Export:
      Name: KnitDevInsightsFastapiServicePublicSecurityGroup
