AWSTemplateFormatVersion: 2010-09-09
Description: "AWS CloudFormation template for creating knit-beta-environment-resources" 

Parameters:
  EnvironmentName:
    Type: String
  TemplateBucketName:
    Type: String
  VpcCidrBlock:
    Type: String

Resources:
  NetworkingBasic:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.amazonaws.com/networking/network-basic.yml"
      Tags:
        - Key: stackId
          Value: !Ref AWS::StackId
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcCidrBlock: !Ref VpcCidrBlock
  NetworkConnectivity:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkingBasic
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.amazonaws.com/networking/network-connectivity.yml"
      Tags:
        - Key: stackId
          Value: !Ref AWS::StackId
      Parameters:
        EnvironmentName: !Ref EnvironmentName
  NetworkALB:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkingBasic
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.amazonaws.com/networking/network-alb.yml"
      Tags:
        - Key: stackId
          Value: !Ref AWS::StackId
      Parameters:
        EnvironmentName: !Ref EnvironmentName
  NetworkNACL:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkingBasic
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.amazonaws.com/networking/network-nacl.yml"
      Tags:
        - Key: stackId
          Value: !Ref AWS::StackId
      Parameters:
        EnvironmentName: !Ref EnvironmentName