AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Script for ECS service and Task Definition'

Parameters:
  ECSClusterName:
    Description: Kindly enter the name of the container
    Type: "String"
    Default: "knit-backend-prod"
  ContainerName:
    Description: Kindly enter the name of the container
    Type: "String"
    Default: "knit-prod-external-connect-container"
  Image:
    Description: Kindly enter the name of the image along with tag 
    Type: "String"
    Default: "020587470742.dkr.ecr.us-east-1.amazonaws.com/knit-prod-external-connect:latest"
  PortMapping:
    Description: Kindly enter the port number for your application  
    Type: "Number"
    Default: "80"
  HealthCheckPath:
    Description: Kindly enter health check path for your application  
    Type: "String" 
    Default: "/docs"
  FamilyName:
    Description: Kindly enter the name of the application so that it can be recognised in creating revisions 
    Type: "String"
    Default: "knit-prod-external-connect"
  ServiceName:
    Description: Kindly enter the service name  
    Type: "String"
    Default: "knit-prod-external-connect"
  BucketName:
    Description: Kindly enter the name of the bucket containing environment files.
    Type: "String"
    Default: "knit-prod-backend-environment-files"
  TargetGroupName:
    Description: Kindly enter the name of the Target group.
    Type: "String"
    Default: "knit-prod-external-connect-tg"
  ApiAccessUrl:
    Description: Kindly enter the url which will be used to access the service.
    Type: "String"
    Default: "externalconnectapi.goknit.com"
  Priority:
    Description: Kindly enter priority number
    Type: "Number"  
    Default: 3


Resources:
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      RoleName: knit-prod-external-connect-ecs-task-role
      Policies:
        - PolicyName: AmazonECSTaskRolePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:ListSecrets
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                  - cloudwatch:GetMetricStatistics
                  - cloudwatch:PutMetricData
                Resource: "*"
              - Effect: Allow
                Action:
                  - secretsmanager:DescribeSecret
                  - secretsmanager:GetResourcePolicy
                  - secretsmanager:ListSecretVersionIds
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:knit_prod_secrete_manager-uzG6aX'
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource: 'arn:aws:ssm:*:*:parameter/AmazonCloudWatch-*'

  Task:
      Type: AWS::ECS::TaskDefinition
      Properties: 
        Family: !Ref FamilyName
        Cpu: 2048
        Memory: 4096
        NetworkMode: awsvpc
        TaskRoleArn: !GetAtt TaskRole.Arn
        RequiresCompatibilities:
          - FARGATE
        ExecutionRoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/knit-prod-ecs-taskexecution-role'
        ContainerDefinitions:
          - Name: !Ref ContainerName
            Image: !Ref Image
            EnvironmentFiles: 
              - Type: "s3"
                Value: !Join [ "", ["arn:aws:s3:::",!Ref BucketName,"/",!Ref ServiceName,".env" ]]
            PortMappings:
              - ContainerPort: !Ref PortMapping
                Protocol: tcp
            LogConfiguration:
              LogDriver: awslogs
              Options:
                awslogs-group: "knit-backend-main-log-group"
                awslogs-region: !Ref 'AWS::Region'
                awslogs-stream-prefix: prod-knit-external-connect-service

  PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup      
    Properties:
     VpcId: vpc-074bb0b6f81390144
     GroupDescription: for ecs containers
     SecurityGroupIngress:
       - SourceSecurityGroupId: sg-006e3455a3195dda4
         IpProtocol: tcp
         FromPort: !Ref PortMapping
         ToPort: !Ref PortMapping   

  DiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Properties: 
      Description: Discovery Service for the Application
      DnsConfig:
        RoutingPolicy: MULTIVALUE
        DnsRecords:
          - TTL: 60
            Type: A
      HealthCheckCustomConfig: 
        FailureThreshold: 1
      Name: !Ref ServiceName
      NamespaceId: ns-o7cfcnsw37mas2rd

  PublicService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Ref ServiceName
      TaskDefinition: !Ref Task
      Cluster: !Sub 'arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${ECSClusterName}'
      LaunchType: FARGATE
      DesiredCount: 1
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 70
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - subnet-03f7e0d21159d4cfe
            - subnet-0ce07f51b93037168
          SecurityGroups:
            - !Ref PublicSecurityGroup
      LoadBalancers:
        - ContainerName: !Ref ContainerName
          ContainerPort: !Ref PortMapping
          TargetGroupArn: !Ref ServiceTargetGroup
      ServiceRegistries:
        - RegistryArn: !GetAtt DiscoveryService.Arn

  ServiceTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Ref TargetGroupName
      VpcId: vpc-074bb0b6f81390144
      Port: !Ref PortMapping
      Protocol: HTTP
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 60
      HealthCheckPath: !Ref HealthCheckPath
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 25
      HealthyThresholdCount: 10
      UnhealthyThresholdCount: 5
      TargetType: ip

  ServiceListenerRule:
    Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ServiceTargetGroup
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - !Ref ApiAccessUrl
      ListenerArn: 'arn:aws:elasticloadbalancing:us-east-1:020587470742:listener/app/knit-external-fast-apis-prod/85241aaff89dee32/62433013621d98a9'
      Priority: !Ref Priority

  ScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn:
      - PublicService
    Properties:
      ServiceNamespace: 'ecs'
      ScalableDimension: 'ecs:service:DesiredCount'
      ResourceId: !Sub 'service/${ECSClusterName}/${ServiceName}'
      MinCapacity: 1
      MaxCapacity: 5
      RoleARN: !Sub 'arn:aws:iam::${AWS::AccountId}:role/knit-prod-auto-scaling-role'

  ScaleDownPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn: ScalableTarget
    Properties:
      PolicyName: !Sub knit-prod-${ECSClusterName}-${ServiceName}-service-scale-down-policy
      PolicyType: StepScaling
      ResourceId: !Sub 'service/${ECSClusterName}/${ServiceName}'
      ScalableDimension: 'ecs:service:DesiredCount'
      ServiceNamespace: 'ecs'
      StepScalingPolicyConfiguration:
        MinAdjustmentMagnitude: 1
        AdjustmentType: 'PercentChangeInCapacity'
        StepAdjustments:
          - MetricIntervalUpperBound: 0
            ScalingAdjustment: -50
        MetricAggregationType: 'Average'
        Cooldown: 60

  ScaleUpPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn: ScalableTarget
    Properties:
      PolicyName: !Sub knit-prod-${ECSClusterName}-${ServiceName}-service-scale-up-policy
      PolicyType: StepScaling
      ResourceId: !Sub 'service/${ECSClusterName}/${ServiceName}'
      ScalableDimension: 'ecs:service:DesiredCount'
      ServiceNamespace: 'ecs'
      StepScalingPolicyConfiguration:
        MinAdjustmentMagnitude: 1
        AdjustmentType: 'PercentChangeInCapacity'
        StepAdjustments:
          - MetricIntervalLowerBound: 40
            MetricIntervalUpperBound: 60
            ScalingAdjustment: 50
          - MetricIntervalLowerBound: 60
            MetricIntervalUpperBound: 75
            ScalingAdjustment: 70
          - MetricIntervalLowerBound: 75
            ScalingAdjustment: 100
        MetricAggregationType: 'Maximum'
        Cooldown: 30

  # Create alarms to trigger the scaling policies
  LowCpuUsageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub knit-prod-low-cpu-${ECSClusterName}-${ServiceName}-service-alarm
      AlarmDescription: !Sub "Low CPU utilization for service ${ServiceName} in cluster ${ECSClusterName}"
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Dimensions:
        - Name: ServiceName
          Value: !Ref 'ServiceName'
        - Name: ClusterName
          Value: !Ref 'ECSClusterName'
      Statistic: Maximum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 20
      ComparisonOperator: LessThanOrEqualToThreshold
      AlarmActions:
        - !Ref ScaleDownPolicy

  HighCpuUsageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub knit-prod-high-cpu-${ECSClusterName}-${ServiceName}-service-alarm
      AlarmDescription: !Sub "High CPU utilization for service ${ServiceName} in cluster ${ECSClusterName}"
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Dimensions:
        - Name: ServiceName
          Value: !Ref 'ServiceName'
        - Name: ClusterName
          Value: !Ref 'ECSClusterName'
      Statistic: Maximum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref ScaleUpPolicy
